wip

diff --git a/bin/dump-maps b/bin/dump-maps
--- a/bin/dump-maps
+++ b/bin/dump-maps
@@ -1,10 +1,12 @@
-#!/usr/bin/env python
+#!/bin/bash
 
-import subprocess
+gtl
 
-raw = subprocess.check_output(['vim', '-c', 'verbose map', '-c', 'qa!'], stderr=subprocess.STDOUT)
-lines = raw.decode('utf-8').split('\n')
+source venv/bin/activate || {
+  echo "Can't activate venv."
+  exit 1
+}
 
-for line in lines:
-  print(line)
+pip install -e .
 
+git_plugin/dump-maps.py
